// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWmqn9eCIgeqz2qc6t9PjQRw0vdny-bXE',
    appId: '1:771329877335:web:6f924e6b5b7c8fccc84a12',
    messagingSenderId: '771329877335',
    projectId: 'my-first-firebase-projec-374e6',
    authDomain: 'my-first-firebase-projec-374e6.firebaseapp.com',
    storageBucket: 'my-first-firebase-projec-374e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQKREp67eKpI2rPcHr-Q3D2EmaByB9Doo',
    appId: '1:771329877335:android:ac0ec53ee5b74d00c84a12',
    messagingSenderId: '771329877335',
    projectId: 'my-first-firebase-projec-374e6',
    storageBucket: 'my-first-firebase-projec-374e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1OvMJ5ge8deuYdehWsrh2FgzwZgcWJSs',
    appId: '1:771329877335:ios:c2ebed06ca2ade1cc84a12',
    messagingSenderId: '771329877335',
    projectId: 'my-first-firebase-projec-374e6',
    storageBucket: 'my-first-firebase-projec-374e6.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1OvMJ5ge8deuYdehWsrh2FgzwZgcWJSs',
    appId: '1:771329877335:ios:c2ebed06ca2ade1cc84a12',
    messagingSenderId: '771329877335',
    projectId: 'my-first-firebase-projec-374e6',
    storageBucket: 'my-first-firebase-projec-374e6.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWmqn9eCIgeqz2qc6t9PjQRw0vdny-bXE',
    appId: '1:771329877335:web:5a65b03f35dbf923c84a12',
    messagingSenderId: '771329877335',
    projectId: 'my-first-firebase-projec-374e6',
    authDomain: 'my-first-firebase-projec-374e6.firebaseapp.com',
    storageBucket: 'my-first-firebase-projec-374e6.firebasestorage.app',
  );
}
